version: '2'

services:
  api:
    build:
      context: springboot
    container_name: api
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"

  db:
    build:
      context: postgres
    container_name: db
    ports:
      - "5432:5432"

  pgadmin_db:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    container_name: pgadmin_db
    links:
      - db
    depends_on:
      - "db"
    ports:
      - "8084:80"